// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Item is the predicate function for item builders.
type Item func(*sql.Selector)

// SystemSummary is the predicate function for systemsummary builders.
type SystemSummary func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// TaskType is the predicate function for tasktype builders.
type TaskType func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
