// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// TaskType is the predicate function for tasktype builders.
type TaskType func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
