// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"github.com/DanielTitkov/tinig-demo-server/internal/repository/entgo/ent/predicate"
	"github.com/DanielTitkov/tinig-demo-server/internal/repository/entgo/ent/systemsummary"
	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
)

// SystemSummaryQuery is the builder for querying SystemSummary entities.
type SystemSummaryQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	unique     []string
	predicates []predicate.SystemSummary
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (ssq *SystemSummaryQuery) Where(ps ...predicate.SystemSummary) *SystemSummaryQuery {
	ssq.predicates = append(ssq.predicates, ps...)
	return ssq
}

// Limit adds a limit step to the query.
func (ssq *SystemSummaryQuery) Limit(limit int) *SystemSummaryQuery {
	ssq.limit = &limit
	return ssq
}

// Offset adds an offset step to the query.
func (ssq *SystemSummaryQuery) Offset(offset int) *SystemSummaryQuery {
	ssq.offset = &offset
	return ssq
}

// Order adds an order step to the query.
func (ssq *SystemSummaryQuery) Order(o ...OrderFunc) *SystemSummaryQuery {
	ssq.order = append(ssq.order, o...)
	return ssq
}

// First returns the first SystemSummary entity in the query. Returns *NotFoundError when no systemsummary was found.
func (ssq *SystemSummaryQuery) First(ctx context.Context) (*SystemSummary, error) {
	sses, err := ssq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(sses) == 0 {
		return nil, &NotFoundError{systemsummary.Label}
	}
	return sses[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ssq *SystemSummaryQuery) FirstX(ctx context.Context) *SystemSummary {
	ss, err := ssq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return ss
}

// FirstID returns the first SystemSummary id in the query. Returns *NotFoundError when no id was found.
func (ssq *SystemSummaryQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ssq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{systemsummary.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (ssq *SystemSummaryQuery) FirstXID(ctx context.Context) int {
	id, err := ssq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only SystemSummary entity in the query, returns an error if not exactly one entity was returned.
func (ssq *SystemSummaryQuery) Only(ctx context.Context) (*SystemSummary, error) {
	sses, err := ssq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(sses) {
	case 1:
		return sses[0], nil
	case 0:
		return nil, &NotFoundError{systemsummary.Label}
	default:
		return nil, &NotSingularError{systemsummary.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ssq *SystemSummaryQuery) OnlyX(ctx context.Context) *SystemSummary {
	ss, err := ssq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return ss
}

// OnlyID returns the only SystemSummary id in the query, returns an error if not exactly one id was returned.
func (ssq *SystemSummaryQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ssq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{systemsummary.Label}
	default:
		err = &NotSingularError{systemsummary.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ssq *SystemSummaryQuery) OnlyIDX(ctx context.Context) int {
	id, err := ssq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SystemSummaries.
func (ssq *SystemSummaryQuery) All(ctx context.Context) ([]*SystemSummary, error) {
	if err := ssq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ssq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ssq *SystemSummaryQuery) AllX(ctx context.Context) []*SystemSummary {
	sses, err := ssq.All(ctx)
	if err != nil {
		panic(err)
	}
	return sses
}

// IDs executes the query and returns a list of SystemSummary ids.
func (ssq *SystemSummaryQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := ssq.Select(systemsummary.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ssq *SystemSummaryQuery) IDsX(ctx context.Context) []int {
	ids, err := ssq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ssq *SystemSummaryQuery) Count(ctx context.Context) (int, error) {
	if err := ssq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ssq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ssq *SystemSummaryQuery) CountX(ctx context.Context) int {
	count, err := ssq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ssq *SystemSummaryQuery) Exist(ctx context.Context) (bool, error) {
	if err := ssq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ssq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ssq *SystemSummaryQuery) ExistX(ctx context.Context) bool {
	exist, err := ssq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ssq *SystemSummaryQuery) Clone() *SystemSummaryQuery {
	return &SystemSummaryQuery{
		config:     ssq.config,
		limit:      ssq.limit,
		offset:     ssq.offset,
		order:      append([]OrderFunc{}, ssq.order...),
		unique:     append([]string{}, ssq.unique...),
		predicates: append([]predicate.SystemSummary{}, ssq.predicates...),
		// clone intermediate query.
		sql:  ssq.sql.Clone(),
		path: ssq.path,
	}
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SystemSummary.Query().
//		GroupBy(systemsummary.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (ssq *SystemSummaryQuery) GroupBy(field string, fields ...string) *SystemSummaryGroupBy {
	group := &SystemSummaryGroupBy{config: ssq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ssq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ssq.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.SystemSummary.Query().
//		Select(systemsummary.FieldCreateTime).
//		Scan(ctx, &v)
//
func (ssq *SystemSummaryQuery) Select(field string, fields ...string) *SystemSummarySelect {
	selector := &SystemSummarySelect{config: ssq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ssq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ssq.sqlQuery(), nil
	}
	return selector
}

func (ssq *SystemSummaryQuery) prepareQuery(ctx context.Context) error {
	if ssq.path != nil {
		prev, err := ssq.path(ctx)
		if err != nil {
			return err
		}
		ssq.sql = prev
	}
	return nil
}

func (ssq *SystemSummaryQuery) sqlAll(ctx context.Context) ([]*SystemSummary, error) {
	var (
		nodes = []*SystemSummary{}
		_spec = ssq.querySpec()
	)
	_spec.ScanValues = func() []interface{} {
		node := &SystemSummary{config: ssq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, ssq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ssq *SystemSummaryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ssq.querySpec()
	return sqlgraph.CountNodes(ctx, ssq.driver, _spec)
}

func (ssq *SystemSummaryQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ssq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (ssq *SystemSummaryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   systemsummary.Table,
			Columns: systemsummary.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: systemsummary.FieldID,
			},
		},
		From:   ssq.sql,
		Unique: true,
	}
	if ps := ssq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ssq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ssq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ssq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ssq *SystemSummaryQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(ssq.driver.Dialect())
	t1 := builder.Table(systemsummary.Table)
	selector := builder.Select(t1.Columns(systemsummary.Columns...)...).From(t1)
	if ssq.sql != nil {
		selector = ssq.sql
		selector.Select(selector.Columns(systemsummary.Columns...)...)
	}
	for _, p := range ssq.predicates {
		p(selector)
	}
	for _, p := range ssq.order {
		p(selector)
	}
	if offset := ssq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ssq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SystemSummaryGroupBy is the builder for group-by SystemSummary entities.
type SystemSummaryGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ssgb *SystemSummaryGroupBy) Aggregate(fns ...AggregateFunc) *SystemSummaryGroupBy {
	ssgb.fns = append(ssgb.fns, fns...)
	return ssgb
}

// Scan applies the group-by query and scan the result into the given value.
func (ssgb *SystemSummaryGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := ssgb.path(ctx)
	if err != nil {
		return err
	}
	ssgb.sql = query
	return ssgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ssgb *SystemSummaryGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := ssgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (ssgb *SystemSummaryGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(ssgb.fields) > 1 {
		return nil, errors.New("ent: SystemSummaryGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := ssgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ssgb *SystemSummaryGroupBy) StringsX(ctx context.Context) []string {
	v, err := ssgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from group-by. It is only allowed when querying group-by with one field.
func (ssgb *SystemSummaryGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ssgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{systemsummary.Label}
	default:
		err = fmt.Errorf("ent: SystemSummaryGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ssgb *SystemSummaryGroupBy) StringX(ctx context.Context) string {
	v, err := ssgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (ssgb *SystemSummaryGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(ssgb.fields) > 1 {
		return nil, errors.New("ent: SystemSummaryGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := ssgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ssgb *SystemSummaryGroupBy) IntsX(ctx context.Context) []int {
	v, err := ssgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from group-by. It is only allowed when querying group-by with one field.
func (ssgb *SystemSummaryGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ssgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{systemsummary.Label}
	default:
		err = fmt.Errorf("ent: SystemSummaryGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ssgb *SystemSummaryGroupBy) IntX(ctx context.Context) int {
	v, err := ssgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (ssgb *SystemSummaryGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(ssgb.fields) > 1 {
		return nil, errors.New("ent: SystemSummaryGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := ssgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ssgb *SystemSummaryGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := ssgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from group-by. It is only allowed when querying group-by with one field.
func (ssgb *SystemSummaryGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ssgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{systemsummary.Label}
	default:
		err = fmt.Errorf("ent: SystemSummaryGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ssgb *SystemSummaryGroupBy) Float64X(ctx context.Context) float64 {
	v, err := ssgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (ssgb *SystemSummaryGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(ssgb.fields) > 1 {
		return nil, errors.New("ent: SystemSummaryGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := ssgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ssgb *SystemSummaryGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := ssgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from group-by. It is only allowed when querying group-by with one field.
func (ssgb *SystemSummaryGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ssgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{systemsummary.Label}
	default:
		err = fmt.Errorf("ent: SystemSummaryGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ssgb *SystemSummaryGroupBy) BoolX(ctx context.Context) bool {
	v, err := ssgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ssgb *SystemSummaryGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ssgb.sqlQuery().Query()
	if err := ssgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ssgb *SystemSummaryGroupBy) sqlQuery() *sql.Selector {
	selector := ssgb.sql
	columns := make([]string, 0, len(ssgb.fields)+len(ssgb.fns))
	columns = append(columns, ssgb.fields...)
	for _, fn := range ssgb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(ssgb.fields...)
}

// SystemSummarySelect is the builder for select fields of SystemSummary entities.
type SystemSummarySelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (sss *SystemSummarySelect) Scan(ctx context.Context, v interface{}) error {
	query, err := sss.path(ctx)
	if err != nil {
		return err
	}
	sss.sql = query
	return sss.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (sss *SystemSummarySelect) ScanX(ctx context.Context, v interface{}) {
	if err := sss.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (sss *SystemSummarySelect) Strings(ctx context.Context) ([]string, error) {
	if len(sss.fields) > 1 {
		return nil, errors.New("ent: SystemSummarySelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := sss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (sss *SystemSummarySelect) StringsX(ctx context.Context) []string {
	v, err := sss.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from selector. It is only allowed when selecting one field.
func (sss *SystemSummarySelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = sss.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{systemsummary.Label}
	default:
		err = fmt.Errorf("ent: SystemSummarySelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (sss *SystemSummarySelect) StringX(ctx context.Context) string {
	v, err := sss.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (sss *SystemSummarySelect) Ints(ctx context.Context) ([]int, error) {
	if len(sss.fields) > 1 {
		return nil, errors.New("ent: SystemSummarySelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := sss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (sss *SystemSummarySelect) IntsX(ctx context.Context) []int {
	v, err := sss.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from selector. It is only allowed when selecting one field.
func (sss *SystemSummarySelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = sss.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{systemsummary.Label}
	default:
		err = fmt.Errorf("ent: SystemSummarySelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (sss *SystemSummarySelect) IntX(ctx context.Context) int {
	v, err := sss.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (sss *SystemSummarySelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(sss.fields) > 1 {
		return nil, errors.New("ent: SystemSummarySelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := sss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (sss *SystemSummarySelect) Float64sX(ctx context.Context) []float64 {
	v, err := sss.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from selector. It is only allowed when selecting one field.
func (sss *SystemSummarySelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = sss.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{systemsummary.Label}
	default:
		err = fmt.Errorf("ent: SystemSummarySelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (sss *SystemSummarySelect) Float64X(ctx context.Context) float64 {
	v, err := sss.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (sss *SystemSummarySelect) Bools(ctx context.Context) ([]bool, error) {
	if len(sss.fields) > 1 {
		return nil, errors.New("ent: SystemSummarySelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := sss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (sss *SystemSummarySelect) BoolsX(ctx context.Context) []bool {
	v, err := sss.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from selector. It is only allowed when selecting one field.
func (sss *SystemSummarySelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = sss.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{systemsummary.Label}
	default:
		err = fmt.Errorf("ent: SystemSummarySelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (sss *SystemSummarySelect) BoolX(ctx context.Context) bool {
	v, err := sss.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (sss *SystemSummarySelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := sss.sqlQuery().Query()
	if err := sss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (sss *SystemSummarySelect) sqlQuery() sql.Querier {
	selector := sss.sql
	selector.Select(selector.Columns(sss.fields...)...)
	return selector
}
