env: dev
db:
  uri: "host=localhost port=5435 user=test dbname=tinig password=pass sslmode=disable"
  driver: postgres
server:
  port: 8000
  host: "0.0.0.0"
auth:
  exp: 72000 # hours
  secret: secret-key
task:
  itemLimit: 10
job: 
  systemSummaryPeriod: 1800 # seconds