// Code generated by entc, DO NOT EDIT.

package tasktype

const (
	// Label holds the string label denoting the tasktype type in the database.
	Label = "task_type"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"

	// EdgeTasks holds the string denoting the tasks edge name in mutations.
	EdgeTasks = "tasks"

	// Table holds the table name of the tasktype in the database.
	Table = "task_types"
	// TasksTable is the table the holds the tasks relation/edge.
	TasksTable = "tasks"
	// TasksInverseTable is the table name for the Task entity.
	// It exists in this package in order to avoid circular dependency with the "task" package.
	TasksInverseTable = "tasks"
	// TasksColumn is the table column denoting the tasks relation/edge.
	TasksColumn = "task_type_tasks"
)

// Columns holds all SQL columns for tasktype fields.
var Columns = []string{
	FieldID,
	FieldCode,
	FieldTitle,
}

var (
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
)
