// Code generated by entc, DO NOT EDIT.

package systemsummary

import (
	"time"
)

const (
	// Label holds the string label denoting the systemsummary type in the database.
	Label = "system_summary"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUsers holds the string denoting the users field in the database.
	FieldUsers = "users"
	// FieldTasks holds the string denoting the tasks field in the database.
	FieldTasks = "tasks"
	// FieldActiveTasks holds the string denoting the active_tasks field in the database.
	FieldActiveTasks = "active_tasks"
	// FieldItems holds the string denoting the items field in the database.
	FieldItems = "items"
	// FieldAvgItemsPerTask holds the string denoting the avg_items_per_task field in the database.
	FieldAvgItemsPerTask = "avg_items_per_task"

	// Table holds the table name of the systemsummary in the database.
	Table = "system_summaries"
)

// Columns holds all SQL columns for systemsummary fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUsers,
	FieldTasks,
	FieldActiveTasks,
	FieldItems,
	FieldAvgItemsPerTask,
}

var (
	// DefaultCreateTime holds the default value on creation for the create_time field.
	DefaultCreateTime func() time.Time
)
